export const StringConstants = {
    diamondIcon: "diamond",
    logout: 'Logout',
    helloText: 'Hello:',
    login_welcome: 'Welcome back!',
    login_sub_title: 'Sign in to your account',
    login_textField_placeholder: 'Enter your username',
    login_nextButton: 'Next',
    login_alert_message: 'Please enter username',
    dashBoardScreen: 'DashboardScreen',
    detailScreen: 'DetailScreen',
    buttonsViewTitleText: '4 Variations of a button',
    pressMeButtonText: 'Press me',
    silideMeButtonText: 'Slide me to continue',
    buttonAlertText: ' button pressed',
    firstAlertText: 'First',
    secondAlertText: 'Second',
    thirdAlertText: 'Third',
    detailSubTitleText: 'Artificial Intelligence (AI) and Machine Learning (ML)',
    detailBodyText: 'Artificial Intelligence, also known as AI, started gaining popularity a decade ago. It has still not slowed down and continues to be one of the leading technologies in 2023. AI is constantly evolving, and newer applications for this emerging technology continue to spring upon the scene. Today’s most popular AI applications are image and speech recognition, navigation programs, voice assistants like Siri and Alexa, and much more. Organisations are looking to use AI to analyse customer and business interactions to derive insights and identify triggers. Machine Learning (ML) is a part of AI and uses supervised learning to learn new functions. It has seen a massive surge in demand for skilled professionals, making it an attractive trend to watch. According to Forrester, AI and Machine Learning will be responsible for 9% of all new jobs in the US by 2025.'
} 
